---
- name: Create a new user with password
  no_log: true
  ansible.builtin.user:
    name: "{{ item.value.name }}"
    password: "{{ item.value.password }}"
    groups: "{{ item.value.groups }}"
    shell: "{{ item.value.shell }}"
    create_home: true
    append: false
  with_dict: "{{ users }}"

- name: Set authorized key
  ansible.posix.authorized_key:
    user: "{{ item.value.name }}"
    key: "{{ item.value.ssh_pub }}"
    state: present
    exclusive: true
  with_dict: "{{ users }}"
