apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
  namespace: my-app-namespace
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app.kubernetes.io/name: my-flask-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: my-flask-app
    spec:
      containers:
        - name: flask-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              protocol: TCP
              containerPort: 8000
          env:
            - name: UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: AUTHOR
              value: "{{ .Values.author }}"

          readinessProbe:
            httpGet:
              path: /readiness
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5

          resources:
            limits:
              cpu: 400m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 128Mi
